# Doorman S3 Firmware
substitutions:
  name: "doorman-s3"
  friendly_name: "Doorman S3"

# Import Doorman Standard Firmware Config
packages:
  AzonInc.Doorman-Standard: github://azoninc/doorman/firmware/configurations/esp32-s3.ha.standard.master.yaml@master

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password