substitutions:
  branch: "local"
  firmware_type: "nuki-bridge"
  api_variant: "custom"
  host_platform: "esp32-s3-quad"

packages:
  host: !include ../hosts/esp32-s3-quad.yaml
  external_components_local: !include ../components/external-components.local.yaml
  rgb_status_led: !include ../components/rgb-status-led.yaml
  rgb_status_led_effects: !include ../components/rgb-status-led.effects.yaml
  base: !include ../base.yaml
  ota_update_esphome: !include ../components/ota-update.esphome.yaml
  api: !include ../components/api.custom.yaml
  pattern_events: !include ../components/pattern-events.yaml
  ring_to_open: !include ../components/ring-to-open.yaml
  ring_to_open_nuki: !include ../components/ring-to-open-nuki.yaml
  intercom_settings: !include ../components/intercom-settings.yaml
  addon_nuki_bridge: !include ../components/nuki-bridge.yaml
  interactive_setup: !include ../components/interactive-setup.yaml