substitutions:
  branch: "local"
  firmware_type: "stock"
  api_variant: "homekit"
  host_platform: "esp32"

packages:
  host: !include ../hosts/esp32.yaml
  external_components_local: !include ../components/external-components.local.yaml
  rgb_status_led: !include ../components/rgb-status-led.yaml
  rgb_status_led_effects: !include ../components/rgb-status-led.effects.yaml
  base: !include ../base.yaml
  webserver_dev: !include ../components/web-server.dev.yaml
  bluedroid_ble: !include ../components/bluedroid-ble.yaml
  ota_update_esphome: !include ../components/ota-update.esphome.yaml
  api: !include ../components/api.homekit.yaml
  debug_utilities: !include ../components/debug-utilities.yaml
  debug_component: !include ../components/debug-component.yaml
  configo: !include ../components/configo.yaml
  pattern_events: !include ../components/pattern-events.yaml
  ring_to_open: !include ../components/ring-to-open.yaml
  ring_to_open_homekit: !include ../components/ring-to-open.homekit.yaml
  indoor_station_settings: !include ../components/indoor-station-settings.yaml
  interactive_setup: !include ../components/interactive-setup.yaml
  outdoor_station: !include ../components/outdoor-station.yaml