substitutions:
  branch: "master"
  firmware_type: "stock"
  api_variant: "mqtt"
  host_platform: "esp32"

packages:
  host: !include ../hosts/esp32.yaml
  external_components: !include ../components/external-components.yaml
  rgb_status_led: !include ../components/rgb-status-led.yaml
  rgb_status_led_effects: !include ../components/rgb-status-led.effects.yaml
  base: !include ../base.yaml
  bluedroid_ble: !include ../components/bluedroid-ble.yaml
  ota_update_esphome: !include ../components/ota-update.esphome.yaml
  ota_update_http: !include ../components/ota-update.http.yaml
  api: !include ../components/api.mqtt.yaml
  pattern_events: !include ../components/pattern-events.yaml
  ring_to_open: !include ../components/ring-to-open.yaml
  intercom_settings: !include ../components/intercom-settings.yaml
  interactive_setup: !include ../components/interactive-setup.yaml