# Doorman Stock Firmware (HomeKit)
# Base Board ESP32-S3-QUAD

# You can change a few options here.
substitutions:
  name: "doorman-s3-local-dev"
  friendly_name: "Doorman S3 (Development)"
  # log_level: "ERROR"
  # led_pin: "GPIO1"
  # rgb_led_pin: "GPIO2"
  # relay_pin: "GPIO42"
  # external_button_pin: "GPIO41"
  # adc_input_pin: "GPIO10"

# Import Doorman Firmware Config
packages:
  AzonInc.Doorman: !include ../configurations/esp32-s3-quad.homekit.stock.local.yaml

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password