# API: HomeKit
   
esphome:
  on_boot:
    then:
      - light.turn_on:
          id: doorman_rgb_status_led
          effect: pulse
          red: 100%
          green: 65%
          blue: 0%
      - wait_until:
          condition:
            wifi.connected:

      - script.execute: homekit_connect


script:
  - id: homekit_connect
    mode: restart
    then:
      # Check if is already paired with HomeKit
      - if:
          condition:
             - homekit.paired:
          then:
            # Regular blue pulse while connecting
            - light.turn_on:
                id: doorman_rgb_status_led
                effect: slow_pulse
                red: 0%
                green: 22%
                blue: 100%
          else:
            # Red/Blue pulse because homekit is not paired
            - light.turn_on:
                id: doorman_rgb_status_led
                effect: error_api
            - logger.log: "Wait for HomeKit pairing..."
            - wait_until:
                condition:
                  homekit.paired:

      - logger.log: "Wait for HomeKit connection..."

      - wait_until:
          condition:
            homekit.connected:

      - logger.log: "HomeKit connected!"

      - light.turn_on:
          id: doorman_rgb_status_led
          effect: none
          red: 0%
          green: 22%
          blue: 100%
          color_brightness: 60%

      - delay: 3s

      - script.execute: update_led

esp32:
  framework:
    sdkconfig_options:
      CONFIG_MBEDTLS_HKDF_C: "y"
      CONFIG_LWIP_MAX_SOCKETS: "16"
      
external_components:
  - source: github://azoninc/doorman@${branch}
    components: [ homekit_base, homekit ]
    refresh: 60s

web_server:
  sorting_groups:
    - id: sorting_group_homekit
      name: "HomeKit Configuration"
      sorting_weight: -2

homekit_base:
  meta:
    name: "Doorman"
    manufacturer: "AzonInc"
    model: "Doorman-S3"
    fw_rev: "2025.5.1"
    serial_number: "DMS3-291-21-998"
  setup_code: '291-21-998'
  setup_id: DMS3
  task_stack_size: 3072
  on_identify:
    - logger.log: "HomeKit identify called"
  on_pairing_started:
    - logger.log: "HomeKit pairing started"
  on_pairing_aborted:
    - logger.log: "HomeKit pairing started"
  on_pairing_timeout:
    - logger.log: "HomeKit pairing timed out"
  on_pairing_completed:
    - logger.log:
        format: "HomeKit paired successfully with: %s"
        args: [ 'x.c_str()' ]
        level: INFO
  on_controller_connected:
    - logger.log:
        format: "HomeKit controller %s connected!"
        args: [ 'x.c_str()' ]
        level: INFO
  on_controller_disconnected:
    - logger.log:
        format: "HomeKit controller %s disconnected!"
        args: [ 'x.c_str()' ]
        level: INFO

button:
  - platform: homekit_base
    factory_reset:
      id: homekit_reset_pairing
      name: "Reset HomeKit Pairing"
      icon: "mdi:link-off"
      web_server:
        sorting_group_id: sorting_group_homekit
        sorting_weight: 4

homekit:
  lock:
    - id: entrance_door
      meta:
        name: "Entrance Door"
        manufacturer: "ESPHome"
        model: "Door Opener"
      on_identify:
        - logger.log:
            format: "Entrance Door identify called"
            level: INFO

    - id: second_entrance_door
      meta:
        name: "Second Entrance Door"
        manufacturer: "ESPHome"
        model: "Door Opener"
      on_identify:
        - logger.log:
            format: "Second Entrance Door identify called"
            level: INFO

  event:
    - id: entrance_doorbell_pattern
      meta:
        name: "Entrance Doorbell"
        manufacturer: "ESPHome"
        model: "Doorbell Event"
      on_identify:
        - logger.log:
            format: "Entrance Doorbell identify called"
            level: INFO
        - tc_bus.send:
            type: floor_call

    - id: second_entrance_doorbell_pattern
      meta:
        name: "Second Entrance Doorbell"
        manufacturer: "ESPHome"
        model: "Doorbell Event"
      on_identify:
        - logger.log:
            format: "Second Entrance Doorbell identify called"
            level: INFO
        - tc_bus.send:
            type: floor_call

    - id: apartment_doorbell_pattern
      meta:
        name: "Apartment Doorbell"
        manufacturer: "ESPHome"
        model: "Doorbell Event"
      on_identify:
        - logger.log:
            format: "Apartment Doorbell identify called"
            level: INFO
        - tc_bus.send:
            type: floor_call