# API: HomeKit

esphome:
  on_boot:
    then:
      - light.turn_on:
          id: doorman_rgb_status_led
          effect: pulse
          red: 100%
          green: 65%
          blue: 0%
      - wait_until:
          condition:
            wifi.connected:
      - light.turn_on:
          id: doorman_rgb_status_led
          effect: none
          red: 100%
          green: 65%
          blue: 0%
      - delay: 3s
      - script.execute: update_led

esp32:
  framework:
    sdkconfig_options:
      CONFIG_MBEDTLS_HKDF_C: "y"
      CONFIG_LWIP_MAX_SOCKETS: "16"
      
external_components:
  - source: github://azoninc/doorman@${branch}
    components: [ homekit_base, homekit ]
    refresh: 60s

web_server:
  sorting_groups:
    - id: sorting_group_homekit
      name: "HomeKit Configuration"
      sorting_weight: -2

homekit_base:
  meta:
    name: "Doorman"
    manufacturer: "AzonInc"
    model: "Doorman-S3"
    fw_rev: "2025.5.1"
  setup_code: '291-21-998'
  setup_id: DMS3

homekit:
  lock:
    - id: entrance_door
      meta:
        name: "Entrance Door"
        manufacturer: "ESPHome"
        model: "Template Lock"
    - id: second_entrance_door
      meta:
        name: "Second Entrance Door"
        manufacturer: "ESPHome"
        model: "Template Lock"

button:
  - platform: homekit_base
    factory_reset:
      id: homekit_reset_pairing
      name: "Reset HomeKit Pairing"
      icon: "mdi:link-off"
      web_server:
        sorting_group_id: sorting_group_homekit
        sorting_weight: 4