# API: MQTT

esphome:
  on_boot:
    then:
      - light.turn_on:
          id: doorman_rgb_status_led
          effect: pulse
          red: 100%
          green: 65%
          blue: 0%
      - wait_until:
          condition:
            wifi.connected:
      - light.turn_on:
          id: doorman_rgb_status_led
          effect: slow_pulse
          red: 0%
          green: 22%
          blue: 100%

      # Try to connect to MQTT
      - script.execute: mqtt_apply_settings

      - wait_until:
          condition:
            mqtt.connected:
      - light.turn_on:
          id: doorman_rgb_status_led
          effect: none
          red: 0%
          green: 22%
          blue: 100%
          color_brightness: 60%
      - delay: 3s
      - script.execute: update_led

web_server:
  sorting_groups:
    - id: sorting_group_mqtt
      name: "MQTT Configuration"
      sorting_weight: -2

text:
  - platform: template
    id: mqtt_broker_address
    name: "MQTT: Broker Address"
    optimistic: true
    min_length: 0
    max_length: 30
    mode: text
    restore_value: true
    initial_value : ""
    entity_category: CONFIG
    web_server:
      sorting_group_id: sorting_group_mqtt

  - platform: template
    id: mqtt_broker_username
    name: "MQTT: Username"
    optimistic: true
    min_length: 0
    max_length: 30
    mode: text
    restore_value: true
    initial_value : ""
    entity_category: CONFIG
    web_server:
      sorting_group_id: sorting_group_mqtt
    
  - platform: template
    id: mqtt_broker_password
    name: "MQTT: Password"
    optimistic: true
    min_length: 0
    max_length: 30
    mode: password
    restore_value: true
    initial_value : ""
    entity_category: CONFIG
    web_server:
      sorting_group_id: sorting_group_mqtt

number:
  - platform: template
    id: mqtt_broker_port
    name: "MQTT: Broker Port"
    optimistic: true
    min_value: 0
    max_value: 65535
    step: 1
    mode: box
    restore_value: true
    initial_value: 1883
    entity_category: CONFIG
    disabled_by_default: true
    web_server:
      sorting_group_id: sorting_group_mqtt

button:
  - platform: template
    id: mqtt_save_settings
    name: "MQTT: Save configuration"
    on_press:
      - script.execute: mqtt_apply_settings
    web_server:
      sorting_group_id: sorting_group_mqtt

mqtt:
  id: mqtt_client
  broker: ""
  username: ""
  password: ""
  enable_on_boot: false
  on_json_message:
    - topic: doorman-s3/send_tc_command_raw
      then:
        - tc_bus.send:
            command: !lambda |-
              int command = 0;
              if (x.containsKey("command"))
                command = x["command"];
              return command;
            is_long: !lambda |-
              bool is_long = false;
              if (x.containsKey("is_long"))
                is_long = x["is_long"];
              return is_long;
              
    - topic: doorman-s3/send_tc_command
      then:
        - tc_bus.send:
            type: !lambda |-
              CommandType commandType = COMMAND_TYPE_UNKNOWN;
              if (x.containsKey("type"))
                commandType = string_to_command_type(x["type"]);
              return commandType;
            address: !lambda |-
              int address = 0;
              if (x.containsKey("address"))
                address = x["address"];
              return address;
            payload: !lambda |-
              int payload = 0;
              if (x.containsKey("payload"))
                payload = x["payload"];
              return payload;
            serial_number: !lambda |-
              int serial_number = 0;
              if (x.containsKey("serial_number"))
                serial_number = x["serial_number"];
              return serial_number;


script:
  - id: mqtt_apply_settings
    then:
      - logger.log: Apply Settings & connect to MQTT
      - lambda: |-
          id(mqtt_client).set_broker_address(id(mqtt_broker_address).state.c_str());
          id(mqtt_client).set_broker_port(id(mqtt_broker_port).state);
          id(mqtt_client).set_username(id(mqtt_broker_username).state.c_str());
          id(mqtt_client).set_password(id(mqtt_broker_password).state.c_str());
      - mqtt.enable: