# Interactive Setup Addon

switch:
  - platform: template
    id: doorman_setup_mode
    device_id: tc_bus_is
    name: Setup Mode
    icon: mdi:account-cog
    restore_mode: RESTORE_DEFAULT_ON
    entity_category: CONFIG
    optimistic: true
    on_turn_on:
      - logger.log: "Setup Step 1: Waiting for door or floor call."
      - script.execute: update_led
    on_turn_off:
      - script.execute: update_led
    web_server:
      sorting_group_id: sorting_group_setup_status
      sorting_weight: 0

binary_sensor:
  - platform: template
    id: setup_status_serial_number
    name: "Status: Serial Number"
    icon: "mdi:list-status"
    lambda: |-
      return id(indoor_station_serial_number).state != 0;
    entity_category: DIAGNOSTIC
    web_server:
      sorting_group_id: sorting_group_setup_status
      sorting_weight: 1

  - platform: template
    id: setup_status_indoor_station_model
    name: "Status: Indoor Station Model"
    icon: "mdi:list-status"
    lambda: |-
      return id(indoor_station_model).state != "None";
    entity_category: DIAGNOSTIC
    web_server:
      sorting_group_id: sorting_group_setup_status
      sorting_weight: 2

  - platform: template
    id: setup_status_entrance_door_address
    name: "Status: Entrance Door"
    icon: "mdi:list-status"
    lambda: |-
      return id(entrance_door_station_address).state != 63;
    entity_category: DIAGNOSTIC
    web_server:
      sorting_group_id: sorting_group_setup_status
      sorting_weight: 3

  - platform: template
    id: setup_status_second_entrance_door_address
    name: "Status: Second Entrance Door"
    icon: "mdi:list-status"
    lambda: |-
      return id(second_entrance_door_station_address).state != 63;
    entity_category: DIAGNOSTIC
    web_server:
      sorting_group_id: sorting_group_setup_status
      sorting_weight: 4


# Extend TC:BUS Component
tc_bus_device:
  - id: !extend tc_bus_indoor_station
    on_identify_complete:
      - if:
          condition:
            - switch.is_on: doorman_setup_mode
          then:
            - script.execute: complete_setup

    on_identify_unknown:
      - if:
          condition:
            - switch.is_on: doorman_setup_mode
          then:
            - logger.log:
                format: "Unknown model detected! Please open an issue and provide your logs in order to implement support for this model."
                level: WARN
            - script.execute: complete_setup

    on_identify_timeout:
      - if:
          condition:
            - switch.is_on: doorman_setup_mode
          then:
            - script.execute: complete_setup

tc_bus:
  on_telegram:
    # Setup mode: Wait for Floor or Door Call
    - if:
        condition:
          - switch.is_on: doorman_setup_mode
          - lambda: "return x.type == TELEGRAM_TYPE_FLOOR_CALL || x.type == TELEGRAM_TYPE_DOOR_CALL;"
        then:
          # Save Serial Number
          - number.set:
              id: indoor_station_serial_number
              value: !lambda "return x.serial_number;"

          # Waiting for ringtone to finish before proceeding
          - delay: 3s

          # Start Identification
          - logger.log: "Setup Step 2: Identifying Indoor Station."
          - tc_bus_device.identify:
              id: tc_bus_indoor_station

    # If no door station id is set, wait for one
    - if:
        condition:
          - lambda: return id(entrance_door_station_address).state == 63 && (x.type == TELEGRAM_TYPE_DOOR_CALL || x.type == TELEGRAM_TYPE_OPEN_DOOR) && x.address != id(entrance_door_station_address).state;
        then:
          - number.set:
              id: entrance_door_station_address
              value: !lambda "return x.address;"
              
    # If no second door station id is set, wait for one
    - if:
        condition:
          - lambda: return id(second_entrance_door_station_address).state == 63 && (x.type == TELEGRAM_TYPE_DOOR_CALL || x.type == TELEGRAM_TYPE_OPEN_DOOR) && x.address != id(entrance_door_station_address).state;
        then:
          - number.set:
              id: second_entrance_door_station_address
              value: !lambda "return x.address;"

script:
  - id: complete_setup
    then:
      - switch.turn_off: doorman_setup_mode

      - light.turn_on:
          id: doorman_rgb_status_led
          red: 0%
          green: 100%
          blue: 10%
          effect: none
          #transition_length: 1s
          brightness: !lambda return id(doorman_rgb_status_led_brightness).state / 100.0;

      - delay: 3s
      
      - script.execute: update_led

      - logger.log: "Setup completed."

  - id: !extend update_led
    then:
      - if:
          condition:
            - switch.is_on: doorman_setup_mode
          then:
            - light.turn_on:
                id: doorman_rgb_status_led
                red: 0%
                green: 100%
                blue: 10%
                effect: pulse