# Nuki Bridge Addon

esphome:
  project:
    name: "AzonInc.Doorman Nuki-Bridge"
  devices:
    - id: nuki_smart_lock
      name: "Nuki Lock"
    - id: nuki_bridge
      name: "Nuki Bridge"
      
# Add External Components
external_components:
  - source: github://uriyacovy/ESPHome_nuki_lock@feat/advanced-lock-settings
    refresh: 60s

web_server:
  sorting_groups:
    - id: sorting_group_nuki_settings_general
      name: "Settings - Nuki Lock - General"
      sorting_weight: -65

    - id: sorting_group_nuki_settings_button_led
      name: "Settings - Nuki Lock - Button & LED"
      sorting_weight: -64

    - id: sorting_group_nuki_settings_calibration
      name: "Settings - Nuki Lock - Calibration"
      sorting_weight: -66

    - id: sorting_group_nuki_settings_fob
      name: "Settings - Nuki Lock - Fob Actions"
      sorting_weight: -62

    - id: sorting_group_nuki_settings_night_mode
      name: "Settings - Nuki Lock - Night Mode"
      sorting_weight: -61

    - id: sorting_group_nuki_bridge_settings
      name: "Settings - Nuki Bridge"
      sorting_weight: -60

    - id: sorting_group_nuki
      name: "Information - Nuki Lock"
      sorting_weight: -10

# Pairing Mode
event:
  - id: !extend doorman_boot_button_event
    on_event:
      - if:
          condition:
            - lambda: !lambda 'return event_type.c_str() == "long_press";'
          then:
            - if:
                condition: nuki_lock.paired
                then:
                  - nuki_lock.unpair:
                      id: apartment_door
                  - lambda: |
                      ESP_LOGI("pairing", "Pairing Mode: TODO");
              
            - nuki_lock.set_pairing_mode: 
                id: apartment_door
                pairing_mode: true

number:
  - platform: template
    id: nuki_security_pin
    device_id: nuki_bridge
    name: "Security Pin"
    icon: "mdi:shield-key"
    mode: box
    step: 1
    min_value: 0
    max_value: 999999
    set_action:
      - nuki_lock.set_security_pin:
          security_pin: !lambda return x;
    web_server:
      sorting_group_id: sorting_group_nuki_bridge_settings
      sorting_weight: 5

switch:
  # For Ultra / Go / Pro / 5th Gen
  - platform: template
    id: nuki_pairing_as_app
    device_id: nuki_bridge
    name: "Pairing as App"
    icon: "mdi:cellphone-key"
    restore_mode: RESTORE_DEFAULT_OFF
    entity_category: CONFIG
    optimistic: true
    web_server:
      sorting_group_id: sorting_group_nuki_bridge_settings
      sorting_weight: 4

# Nuki Lock Bridge
lock:
  - platform: nuki_lock
    id: apartment_door
    device_id: nuki_smart_lock
    name: Apartment Door
    icon: "mdi:door"
    web_server:
      sorting_group_id: sorting_group_controls
      sorting_weight: 3

    # Component Settings
    event: nuki
    pairing_as_app: !lambda return id(nuki_pairing_as_app).state;
    pairing_mode_timeout: 300s
    query_interval_config: 3600s
    query_interval_auth_data: 7200s
    ble_general_timeout: 3s
    ble_command_timeout: 3s

    # Nuki Status Sensors
    battery_level:
      id: nuki_battery_level
      device_id: nuki_smart_lock
      name: "Battery Level"
      web_server:
        sorting_group_id: sorting_group_nuki
        sorting_weight: 1
        
    battery_critical:
      id: nuki_battery_critical
      device_id: nuki_smart_lock
      name: "Battery Critical"
      web_server:
        sorting_group_id: sorting_group_nuki
        sorting_weight: 2

    bt_signal_strength:
      id: nuki_bluetooth_signal_strength
      device_id: nuki_smart_lock
      name: "Bluetooth Signal"
      web_server:
        sorting_group_id: sorting_group_nuki
        sorting_weight: 3

    door_sensor:
      id: nuki_door_sensor
      device_id: nuki_smart_lock
      name: "Door Sensor"
      disabled_by_default: true
      web_server:
        sorting_group_id: sorting_group_nuki
        sorting_weight: 4

    door_sensor_state:
      id: nuki_door_sensor_state
      device_id: nuki_smart_lock
      name: "Door Sensor: State"
      disabled_by_default: true
      web_server:
        sorting_group_id: sorting_group_nuki
        sorting_weight: 5

    last_unlock_user:
      id: nuki_last_unlock_user
      device_id: nuki_smart_lock
      name: "Last Unlock User"
      web_server:
        sorting_group_id: sorting_group_nuki
        sorting_weight: 6

    last_lock_action:
      id: nuki_last_lock_action
      device_id: nuki_smart_lock
      name: "Last Lock Action"
      disabled_by_default: true
      web_server:
        sorting_group_id: sorting_group_nuki
        sorting_weight: 7

    last_lock_action_trigger:
      id: nuki_last_lock_action_trigger
      device_id: nuki_smart_lock
      name: "Last Lock Action Trigger"
      disabled_by_default: true
      web_server:
        sorting_group_id: sorting_group_nuki
        sorting_weight: 8

    # General
    advertising_mode:
      id: nuki_advertising_mode
      device_id: nuki_smart_lock
      name: "Advertising Mode"
      disabled_by_default: true
      web_server:
        sorting_group_id: sorting_group_nuki_settings_general
        sorting_weight: 100

    # Button & LED
    pairing_enabled:
      id: nuki_button_pairing_enabled
      device_id: nuki_smart_lock
      name: "Button: Bluetooth Pairing"
      disabled_by_default: true
      web_server:
        sorting_group_id: sorting_group_nuki_settings_button_led
        sorting_weight: 10

    button_enabled:
      id: nuki_button_locking_operations
      device_id: nuki_smart_lock
      name: "Button: Locking operations"
      disabled_by_default: true
      web_server:
        sorting_group_id: sorting_group_nuki_settings_button_led
        sorting_weight: 11

    single_buton_press_action:
      id: nuki_single_button_press_action
      device_id: nuki_smart_lock
      name: "Button: Single Press Action"
      disabled_by_default: true
      web_server:
        sorting_group_id: sorting_group_nuki_settings_button_led
        sorting_weight: 12

    double_buton_press_action:
      id: nuki_double_button_press_action
      device_id: nuki_smart_lock
      name: "Button: Double Press Action"
      disabled_by_default: true
      web_server:
        sorting_group_id: sorting_group_nuki_settings_button_led
        sorting_weight: 13

    led_brightness:
      id: nuki_led_brightness
      device_id: nuki_smart_lock
      name: "LED: Brightness"
      disabled_by_default: true
      mode: slider
      web_server:
        sorting_group_id: sorting_group_nuki_settings_button_led
        sorting_weight: 14

    led_enabled:
      id: nuki_led_enabled
      device_id: nuki_smart_lock
      name: "LED: Signal"
      disabled_by_default: true
      web_server:
        sorting_group_id: sorting_group_nuki_settings_button_led
        sorting_weight: 15

    # Night Mode
    night_mode_enabled:
      id: nuki_night_mode
      device_id: nuki_smart_lock
      name: "Night Mode"
      disabled_by_default: true
      web_server:
        sorting_group_id: sorting_group_nuki_settings_night_mode
        sorting_weight: 40

    night_mode_auto_lock_enabled:
      id: nuki_night_mode_auto_lock_enabled
      device_id: nuki_smart_lock
      name: "Night Mode: Auto Lock"
      disabled_by_default: true
      web_server:
        sorting_group_id: sorting_group_nuki_settings_night_mode
        sorting_weight: 41

    night_mode_auto_unlock_disabled:
      id: nuki_night_mode_auto_unlock_disabled
      device_id: nuki_smart_lock
      name: "Night Mode: Reject Auto Unlock"
      disabled_by_default: true
      web_server:
        sorting_group_id: sorting_group_nuki_settings_night_mode
        sorting_weight: 42

    night_mode_immediate_lock_on_start_enabled:
      id: nuki_night_mode_immediate_lock_on_start
      device_id: nuki_smart_lock
      name: "Night Mode: Lock at Start Time"
      disabled_by_default: true
      web_server:
        sorting_group_id: sorting_group_nuki_settings_night_mode
        sorting_weight: 43

    # Fob Actions
    fob_action_1:
      id: nuki_fob_action_1
      device_id: nuki_smart_lock
      name: "Fob: Action 1"
      disabled_by_default: true
      web_server:
        sorting_group_id: sorting_group_nuki_settings_fob
        sorting_weight: 50

    fob_action_2:
      id: nuki_fob_action_2
      device_id: nuki_smart_lock
      name: "Fob: Action 2"
      disabled_by_default: true
      web_server:
        sorting_group_id: sorting_group_nuki_settings_fob
        sorting_weight: 51

    fob_action_3:
      id: nuki_fob_action_3
      device_id: nuki_smart_lock
      name: "Fob: Action 3"
      disabled_by_default: true
      web_server:
        sorting_group_id: sorting_group_nuki_settings_fob
        sorting_weight: 52

    # Auto Lock
    auto_lock_enabled:
      id: nuki_auto_lock
      device_id: nuki_smart_lock
      name: "Auto Lock"
      disabled_by_default: true
      web_server:
        sorting_group_id: sorting_group_nuki_settings_general
        sorting_weight: 60

    auto_lock_timeout:
      id: nuki_auto_lock_timeout
      device_id: nuki_smart_lock
      name: "Auto Lock: Timeout"
      disabled_by_default: true
      mode: slider
      web_server:
        sorting_group_id: sorting_group_nuki_settings_general
        sorting_weight: 61

    immediate_auto_lock_enabled:
      id: nuki_immediate_auto_lock
      device_id: nuki_smart_lock
      name: "Auto Lock: Immediately"
      disabled_by_default: true
      web_server:
        sorting_group_id: sorting_group_nuki_settings_general
        sorting_weight: 62

    auto_unlock_disabled:
      id: nuki_auto_unlock_disabled
      device_id: nuki_smart_lock
      name: "Auto Unlock: Disable"
      disabled_by_default: true
      web_server:
        sorting_group_id: sorting_group_nuki_settings_general
        sorting_weight: 63

    # Advanced Lock Calibration
    auto_unlatch: # Knob or Handle
      id: nuki_auto_unlatch
      device_id: nuki_smart_lock
      name: "Auto unlatch"
      disabled_by_default: true
      web_server:
        sorting_group_id: sorting_group_nuki_settings_calibration
        sorting_weight: 90

    unlatch_duration:
      id: nuki_unlatch_duration
      device_id: nuki_smart_lock
      name: "Unlatch Duration"
      disabled_by_default: true
      mode: slider
      web_server:
        sorting_group_id: sorting_group_nuki_settings_calibration
        sorting_weight: 91

    detached_cylinder_enabled:
      id: nuki_detached_cylinder
      device_id: nuki_smart_lock
      name: "Detached Cylinder"
      disabled_by_default: true
      web_server:
        sorting_group_id: sorting_group_nuki_settings_calibration
        sorting_weight: 92

    single_lock_enabled:
      id: nuki_single_lock
      device_id: nuki_smart_lock
      name: "Single Lock"
      disabled_by_default: true
      web_server:
        sorting_group_id: sorting_group_nuki_settings_calibration
        sorting_weight: 93

    unlocked_position_offset:
      id: nuki_unlocked_position_offset
      device_id: nuki_smart_lock
      name: "Unlocked Position Offset"
      disabled_by_default: true
      mode: slider
      web_server:
        sorting_group_id: sorting_group_nuki_settings_calibration
        sorting_weight: 94

    single_locked_position_offset:
      id: nuki_single_locked_position_offset
      device_id: nuki_smart_lock
      name: "Single Locked Position Offset"
      disabled_by_default: true
      mode: slider
      web_server:
        sorting_group_id: sorting_group_nuki_settings_calibration
        sorting_weight: 95

    locked_position_offset:
      id: nuki_locked_position_offset
      device_id: nuki_smart_lock
      name: "Locked Position Offset"
      disabled_by_default: true
      mode: slider
      web_server:
        sorting_group_id: sorting_group_nuki_settings_calibration
        sorting_weight: 96

    unlocked_to_locked_transition_offset:
      id: nuki_unlocked_to_locked_transition_offset
      device_id: nuki_smart_lock
      name: "Unlocked To Locked Transition Offset"
      disabled_by_default: true
      mode: slider
      web_server:
        sorting_group_id: sorting_group_nuki_settings_calibration
        sorting_weight: 97

    request_calibration:
      id: nuki_request_calibration
      device_id: nuki_bridge
      name: "Request Calibration"
      disabled_by_default: true
      web_server:
        sorting_group_id: sorting_group_nuki_settings_calibration
        sorting_weight: 98

    # Bridge Settings
    paired:
      id: nuki_paired
      device_id: nuki_bridge
      name: "Paired"
      web_server:
        sorting_group_id: sorting_group_nuki_bridge_settings
        sorting_weight: 1

    connected: 
      id: nuki_connected
      device_id: nuki_bridge
      name: "Connected"
      web_server:
        sorting_group_id: sorting_group_nuki_bridge_settings
        sorting_weight: 2

    pairing_mode:
      id: nuki_pairing_mode
      device_id: nuki_bridge
      name: "Pairing Mode"
      web_server:
        sorting_group_id: sorting_group_nuki_bridge_settings
        sorting_weight: 3

    pin_status:
      id: nuki_pin_status
      device_id: nuki_bridge
      name: "Security Pin Status"
      web_server:
        sorting_group_id: sorting_group_nuki_bridge_settings
        sorting_weight: 6

    unpair:
      id: nuki_unpair_device
      device_id: nuki_bridge
      name: "Unpair Device"
      disabled_by_default: true
      web_server:
        sorting_group_id: sorting_group_nuki_bridge_settings
        sorting_weight: 7

    on_pairing_mode_on_action:
      - script.execute: update_led

    on_pairing_mode_off_action:
      - script.execute: update_led
    
    on_paired_action:
      - light.turn_on:
          id: doorman_rgb_status_led
          red: 100%
          green: 0%
          blue: 100%
          effect: none
          #transition_length: 1s
          brightness: !lambda return id(doorman_rgb_status_led_brightness).state / 100.0;
      - delay: 3s
      - script.execute: update_led

script:
  - id: !extend update_led
    then:
      - if:
          condition:
            - switch.is_on: nuki_pairing_mode
          then:
            - light.turn_on:
                id: doorman_rgb_status_led
                red: 100%
                green: 0%
                blue: 100%
                effect: pulse
