# OTA Updates Addon - HTTP

substitutions:
  update_url_stable: "https://doorman.azon.ai/firmware/release/${host_platform}.${api_variant}.${firmware_type}/manifest.json"
  update_url_dev: "https://dev.doorman.azon.ai/firmware/release/${host_platform}.${api_variant}.${firmware_type}/manifest.json"

http_request:
  verify_ssl: false

ota:
  - platform: http_request
    id: ota_http_request
    
update:
  - platform: http_request
    id: update_http_request
    icon: "mdi:update"
    name: Doorman Firmware
    source: ${update_url_stable}
    update_interval: 1h
    on_update_available:
      - logger.log: "A new Doorman Firmware Update is available!"
    disabled_by_default: false
    web_server:
      sorting_group_id: sorting_group_system
      sorting_weight: -4

button:
  - platform: template
    id: update_install
    name: "Install Update"
    icon: "mdi:auto-fix"
    on_press:
      - if:
          condition:
            - update.is_available:
                id: update_http_request
          then:
            - update.perform: update_http_request
          else:
            - logger.log: "No update available"

switch:
  - platform: template
    id: dev_firmware
    name: Experimental firmware
    icon: "mdi:test-tube"
    entity_category: CONFIG
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - logger.log: "OTA update source set to dev"
      - lambda: id(update_http_request).set_source_url(to_string("${update_url_dev}"));
      - component.update: update_http_request
    on_turn_off:
      - logger.log: "OTA update source set to master"
      - lambda: id(update_http_request).set_source_url(to_string("${update_url_stable}"));
      - component.update: update_http_request
    disabled_by_default: true
    web_server:
      sorting_group_id: sorting_group_system
      sorting_weight: -3