# Ring To Open Addon

event:
  - id: !extend entrance_doorbell_pattern
    on_event:
      # Ring To Open Action
      - if:
          condition:
            - switch.is_on: rto_entrance_door
            - lambda: !lambda 'return event_type.c_str() == id(rto_entrance_door_pattern_condition).state;'
          then:
            # Deactivate Ring To Open when Ring once is selected
            - if:
                condition:
                  - lambda: !lambda 'return id(rto_entrance_door_timeout_mode).state == "Ring once";'
                then:
                  - switch.turn_off: rto_entrance_door

            # If delay is 60 seconds, use random delay from 5 to 15 seconds
            - if:
                condition:
                  number.in_range:
                    id: rto_entrance_door_delay
                    above: 59
                then:
                  - delay: !lambda "return 5000 + (rand() % 10000);"
                else:
                  - delay: !lambda "return (id(rto_entrance_door_delay).state*1000) + 300;"

            - script.execute: rto_entrance_door_action


  - id: !extend second_entrance_doorbell_pattern
    on_event:
      # Ring To Open Action
      - if:
          condition:
            - switch.is_on: rto_second_entrance_door
            - lambda: !lambda 'return event_type.c_str() == id(rto_second_entrance_door_pattern_condition).state;'
          then:
            # Deactivate Ring To Open when Ring once is selected
            - if:
                condition:
                  - lambda: !lambda 'return id(rto_second_entrance_door_timeout_mode).state == "Ring once";'
                then:
                  - switch.turn_off: rto_second_entrance_door

            # If delay is 60 seconds, use random delay from 5 to 15 seconds
            - if:
                condition:
                  number.in_range:
                    id: rto_second_entrance_door_delay
                    above: 59
                then:
                  - delay: !lambda "return 5000 + (rand() % 10000);"
                else:
                  - delay: !lambda "return (id(rto_second_entrance_door_delay).state*1000) + 300;"

            - script.execute: rto_second_entrance_door_action

  - id: !extend apartment_doorbell_pattern
    on_event:
      # Ring To Open Action
      - if:
          condition:
            - switch.is_on: rto_apartment_door
            - lambda: !lambda 'return event_type.c_str() == id(rto_apartment_door_pattern_condition).state;'
          then:
            # Deactivate Ring To Open when Ring once is selected
            - if:
                condition:
                  - lambda: !lambda 'return id(rto_apartment_door_timeout_mode).state == "Ring once";'
                then:
                  - switch.turn_off: rto_apartment_door

            # If delay is 60 seconds, use random delay from 5 to 15 seconds
            - if:
                condition:
                  number.in_range:
                    id: rto_apartment_door_delay
                    above: 59
                then:
                  - delay: !lambda "return 5000 + (rand() % 10000);"
                else:
                  - delay: !lambda "return (id(rto_apartment_door_delay).state*1000) + 300;"

            - script.execute: rto_apartment_door_action

binary_sensor:
  - id: !extend function_button
    on_press:
      - if:
          condition:
            - lambda: !lambda 'return id(rto_toggle_trigger).state != "Function Button";'
          then:
            - switch.toggle: rto_entrance_door
            - switch.toggle: rto_second_entrance_door
            - delay: 300ms

            # Confirm Ring To Open activation
            - if: 
                condition:
                  - switch.is_on: rto_entrance_door
                  - switch.is_on: rto_second_entrance_door
                  - switch.is_on: rto_confirmation
                then:
                  - tc_bus.send:
                      type: floor_call

            # Reset to prevent address conflict
            - tc_bus.send:
                type: reset


number:
  # Setting for each Door: Entrance Door
  - platform: template
    name: "RTO: Entrance Door - Delay"
    id: rto_entrance_door_delay
    disabled_by_default: true
    icon: "mdi:clock-end"
    mode: slider
    min_value: 0
    max_value: 60
    step: 1
    optimistic: true
    restore_value: true
    initial_value: 0
    unit_of_measurement: seconds
    entity_category: CONFIG
    web_server:
      sorting_group_id: sorting_group_doorman_settings

  # Setting for each Door - Second Entrance Door
  - platform: template
    name: "RTO: Second Entrance Door - Delay"
    id: rto_second_entrance_door_delay
    disabled_by_default: true
    icon: "mdi:clock-end"
    mode: slider
    min_value: 0
    max_value: 60
    step: 1
    optimistic: true
    restore_value: true
    initial_value: 0
    unit_of_measurement: seconds
    entity_category: CONFIG
    web_server:
      sorting_group_id: sorting_group_doorman_settings

  # Setting for each Door - Apartment Door
  - platform: template
    name: "RTO: Apartment Door - Delay"
    id: rto_apartment_door_delay
    disabled_by_default: true
    internal: true
    icon: "mdi:clock-end"
    mode: slider
    min_value: 0
    max_value: 60
    step: 1
    optimistic: true
    restore_value: true
    initial_value: 0
    unit_of_measurement: seconds
    entity_category: CONFIG
    web_server:
      sorting_group_id: sorting_group_doorman_settings


switch:
  # Global Setting
  - platform: template
    id: rto_quick_toggle
    name: "Ring To Open"
    icon: "mdi:checkbox-marked-circle-auto-outline"
    restore_mode: RESTORE_DEFAULT_OFF
    lambda: |-
      if(id(rto_quick_toggle_doors).state == "Entrance") {
        return id(rto_entrance_door).state;
      } else if(id(rto_quick_toggle_doors).state == "Second Entrance") {
        return id(rto_second_entrance_door).state;
      } else if(id(rto_quick_toggle_doors).state == "Any Entrance") {
        return id(rto_entrance_door).state || id(rto_second_entrance_door).state;
      } else if(id(rto_quick_toggle_doors).state == "Apartment") {
        return id(rto_apartment_door).state;
      } else if(id(rto_quick_toggle_doors).state == "Any Entrance & Apartment") {
        return id(rto_entrance_door).state || id(rto_second_entrance_door).state || id(rto_apartment_door).state;
      }
      return false;
    turn_on_action:
      - lambda: |-
          if(id(rto_quick_toggle_doors).state == "Entrance") {
            id(rto_entrance_door).turn_on();
          } else if(id(rto_quick_toggle_doors).state == "Second Entrance") {
            id(rto_second_entrance_door).turn_on();
          } else if(id(rto_quick_toggle_doors).state == "Any Entrance") {
            id(rto_entrance_door).turn_on();
            id(rto_second_entrance_door).turn_on();
          } else if(id(rto_quick_toggle_doors).state == "Apartment") {
            id(rto_apartment_door).turn_on();
          } else if(id(rto_quick_toggle_doors).state == "Any Entrance & Apartment") {
            id(rto_entrance_door).turn_on();
            id(rto_second_entrance_door).turn_on();
            id(rto_apartment_door).turn_on();
          }
    turn_off_action:
      - lambda: |-
          if(id(rto_quick_toggle_doors).state == "Entrance") {
            id(rto_entrance_door).turn_off();
          } else if(id(rto_quick_toggle_doors).state == "Second Entrance") {
            id(rto_second_entrance_door).turn_off();
          } else if(id(rto_quick_toggle_doors).state == "Any Entrance") {
            id(rto_entrance_door).turn_off();
            id(rto_second_entrance_door).turn_off();
          } else if(id(rto_quick_toggle_doors).state == "Apartment") {
            id(rto_apartment_door).turn_off();
          } else if(id(rto_quick_toggle_doors).state == "Any Entrance & Apartment") {
            id(rto_entrance_door).turn_off();
            id(rto_second_entrance_door).turn_off();
            id(rto_apartment_door).turn_off();
          }
    web_server:
      sorting_group_id: sorting_group_doorman_settings

  # Setting for each Door - Entrance Door
  - platform: template
    id: rto_entrance_door
    name: "RTO: Entrance Door"
    icon: "mdi:checkbox-marked-circle-auto-outline"
    restore_mode: RESTORE_DEFAULT_OFF
    disabled_by_default: true
    optimistic: true
    turn_on_action:
      - script.execute: rto_entrance_door_timer
    turn_off_action:
      - script.stop: rto_entrance_door_timer
    on_turn_on:
      - script.execute: update_led
    on_turn_off:
      - script.execute: update_led
    web_server:
      sorting_group_id: sorting_group_doorman_settings

  # Setting for each Door - Second Entrance Door
  - platform: template
    id: rto_second_entrance_door
    name: "RTO: Second Entrance Door"
    icon: "mdi:checkbox-marked-circle-auto-outline"
    restore_mode: RESTORE_DEFAULT_OFF
    disabled_by_default: true
    optimistic: true
    turn_on_action:
      - script.execute: rto_second_entrance_door_timer
    turn_off_action:
      - script.stop: rto_second_entrance_door_timer
    on_turn_on:
      - script.execute: update_led
    on_turn_off:
      - script.execute: update_led
    web_server:
      sorting_group_id: sorting_group_doorman_settings

  # Setting for each Door - Apartment Door
  - platform: template
    id: rto_apartment_door
    name: "RTO: Apartment Door"
    disabled_by_default: true
    internal: true
    icon: "mdi:checkbox-marked-circle-auto-outline"
    restore_mode: RESTORE_DEFAULT_OFF
    optimistic: true
    turn_on_action:
      - script.execute: rto_apartment_door_timer
    turn_off_action:
      - script.stop: rto_apartment_door_timer
    on_turn_on:
      - script.execute: update_led
    on_turn_off:
      - script.execute: update_led
    web_server:
      sorting_group_id: sorting_group_doorman_settings

  # Global Setting for all Doors
  - platform: template
    id: rto_confirmation
    name: "RTO: Confirmation"
    icon: "mdi:bell-check"
    restore_mode: RESTORE_DEFAULT_OFF
    optimistic: true
    entity_category: CONFIG
    disabled_by_default: true
    web_server:
      sorting_group_id: sorting_group_doorman_settings

  # Global Setting for all Doors
  - platform: template
    id: rto_led_status
    name: "RTO: Display Status"
    icon: "mdi:led-on"
    restore_mode: RESTORE_DEFAULT_ON
    optimistic: true
    entity_category: CONFIG
    disabled_by_default: true
    web_server:
      sorting_group_id: sorting_group_doorman_settings

select:
  - platform: template
    id: rto_quick_toggle_doors
    name: "RTO: Quick Toggle - Door Selection"
    icon: "mdi:door"
    optimistic: true
    options:
      - Entrance Door
      - Second Entrance
      - Any Entrance
      - Apartment
      - Any Entrance & Apartment
    initial_option: "Any Entrance"
    entity_category: CONFIG
    web_server:
      sorting_group_id: sorting_group_doorman_settings

  # Setting for each Door - Entrance Door
  - platform: template
    id: rto_entrance_door_timeout_mode
    name: "RTO: Entrance Door - Timeout"
    icon: "mdi:clock-fast"
    optimistic: true
    options:
      - Never
      - Ring once
      - 5 minutes
      - 10 minutes
      - 15 minutes
      - 20 minutes
      - 25 minutes
      - 30 minutes
      - 35 minutes
      - 40 minutes
      - 45 minutes
      - 50 minutes
      - 55 minutes
      - 60 minutes
    initial_option: Never
    entity_category: CONFIG
    web_server:
      sorting_group_id: sorting_group_doorman_settings

  # Setting for each Door - Second Entrance Door
  - platform: template
    id: rto_second_entrance_door_timeout_mode
    name: "RTO: Second Entrance Door - Timeout"
    icon: "mdi:clock-fast"
    disabled_by_default: true
    optimistic: true
    options:
      - Never
      - Ring once
      - 5 minutes
      - 10 minutes
      - 15 minutes
      - 20 minutes
      - 25 minutes
      - 30 minutes
      - 35 minutes
      - 40 minutes
      - 45 minutes
      - 50 minutes
      - 55 minutes
      - 60 minutes
    initial_option: Never
    entity_category: CONFIG
    web_server:
      sorting_group_id: sorting_group_doorman_settings

  # Setting for each Door - Apartment Door
  - platform: template
    id: rto_apartment_door_timeout_mode
    internal: true
    name: "RTO: Apartment Door - Timeout"
    icon: "mdi:clock-fast"
    optimistic: true
    options:
      - Never
      - Ring once
      - 5 minutes
      - 10 minutes
      - 15 minutes
      - 20 minutes
      - 25 minutes
      - 30 minutes
      - 35 minutes
      - 40 minutes
      - 45 minutes
      - 50 minutes
      - 55 minutes
      - 60 minutes
    initial_option: Never
    entity_category: CONFIG
    web_server:
      sorting_group_id: sorting_group_doorman_settings

  # Setting for each Door - Entrance Door
  - platform: template
    id: rto_entrance_door_pattern_condition
    name: "RTO: Entrance Door - Pattern"
    icon: "mdi:gesture-tap-button"
    disabled_by_default: true
    optimistic: true
    options:
      - single
      - double
      - triple
    initial_option: single
    entity_category: CONFIG
    web_server:
      sorting_group_id: sorting_group_doorman_settings

  # Setting for each Door - Second Entrance Door
  - platform: template
    id: rto_second_entrance_door_pattern_condition
    name: "RTO: Second Entrance Door - Pattern"
    icon: "mdi:gesture-tap-button"
    disabled_by_default: true
    optimistic: true
    options:
      - single
      - double
      - triple
    initial_option: single
    entity_category: CONFIG
    web_server:
      sorting_group_id: sorting_group_doorman_settings

  # Setting for each Door - Apartment Door
  - platform: template
    id: rto_apartment_door_pattern_condition
    name: "RTO: Apartment Door - Pattern"
    internal: true
    icon: "mdi:gesture-tap-button"
    disabled_by_default: true
    optimistic: true
    options:
      - single
      - double
      - triple
    initial_option: single
    entity_category: CONFIG
    web_server:
      sorting_group_id: sorting_group_doorman_settings

  # Global Setting
  - platform: template
    id: rto_toggle_trigger
    name: "RTO: Quick Toggle - Trigger"
    icon: "mdi:circle-outline"
    optimistic: true
    options:
      - Manual
      - Function Button
    initial_option: Manual
    restore_value: true
    entity_category: CONFIG
    disabled_by_default: true
    web_server:
      sorting_group_id: sorting_group_doorman_settings

script:
  - id: rto_entrance_door_timer
    then:
      # Turn off Ring To Open Mode after selected time
      - if:
          condition:
            - lambda: !lambda 'return id(rto_entrance_door_timeout_mode).state != "Never" && id(rto_entrance_door_timeout_mode).state != "Ring once";'
          then:
            - delay: !lambda |-
                std::string str = id(rto_entrance_door_timeout_mode).state;
                std::vector<std::string> v;
                char * token;
                char seps[] = " ";
                token = strtok (&str[0],seps);
                while (token != NULL)
                {
                  v.push_back(token);
                  token = strtok (NULL, seps);
                }
                ESP_LOGD("main", "Ring To Open will stay turned on for %s minutes", v[0].c_str());
                return std::stoi(v[0].c_str()) * 60 * 1000;
            - switch.turn_off: rto_entrance_door

  - id: rto_second_entrance_door_timer
    then:
      # Turn off Ring To Open Mode after selected time
      - if:
          condition:
            - lambda: !lambda 'return id(rto_second_entrance_door_timeout_mode).state != "Never" && id(rto_second_entrance_door_timeout_mode).state != "Ring once";'
          then:
            - delay: !lambda |-
                std::string str = id(rto_second_entrance_door_timeout_mode).state;
                std::vector<std::string> v;
                char * token;
                char seps[] = " ";
                token = strtok (&str[0],seps);
                while (token != NULL)
                {
                  v.push_back(token);
                  token = strtok (NULL, seps);
                }
                ESP_LOGD("main", "Ring To Open will stay turned on for %s minutes", v[0].c_str());
                return std::stoi(v[0].c_str()) * 60 * 1000;
            - switch.turn_off: rto_second_entrance_door

  - id: rto_apartment_door_timer
    then:
      # Turn off Ring To Open Mode after selected time
      - if:
          condition:
            - lambda: !lambda 'return id(rto_apartment_door_timeout_mode).state != "Never" && id(rto_apartment_door_timeout_mode).state != "Ring once";'
          then:
            - delay: !lambda |-
                std::string str = id(rto_apartment_door_timeout_mode).state;
                std::vector<std::string> v;
                char * token;
                char seps[] = " ";
                token = strtok (&str[0],seps);
                while (token != NULL)
                {
                  v.push_back(token);
                  token = strtok (NULL, seps);
                }
                ESP_LOGD("main", "Ring To Open will stay turned on for %s minutes", v[0].c_str());
                return std::stoi(v[0].c_str()) * 60 * 1000;
            - switch.turn_off: rto_apartment_door

  - id: rto_entrance_door_action
    then:
      - tc_bus.send:
          type: open_door
          address: !lambda "return id(entrance_door_station_id).state;"

  - id: rto_second_entrance_door_action
    then:
      - tc_bus.send:
          type: open_door
          address: !lambda "return id(second_entrance_door_station_id).state;"

  - id: rto_apartment_door_action
    then:
      - logger.log: "RTO: Apartment Door Action"

  - id: !extend update_led
    then:
      - if:
          condition:
            - switch.is_on: rto_entrance_door
            - switch.is_on: rto_led_status
          then:
            - light.turn_on:
                id: doorman_rgb_status_led
                red: 100%
                green: 100%
                blue: 3%
                effect: slow_pulse