# Ring To Open Addon

binary_sensor:
  - id: !extend apartment_doorbell
    on_press:
      then:
        # Ring To Open Action
        - if:
            condition:
              - switch.is_on: doorman_ring_to_open
              - lambda: !lambda 'return id(doorman_ring_to_open_door_trigger).state == "Apartment" || id(doorman_ring_to_open_door_trigger).state == "Any";'
            then:
              # Deactivate Ring To Open when Ring once is selected
              - if:
                  condition:
                    - lambda: !lambda 'return id(doorman_ring_to_open_timeout_mode).state == "Ring once";'
                  then:
                    - switch.turn_off: doorman_ring_to_open

              # If delay is 60 seconds, use random delay from 5 to 15 seconds
              - if:
                  condition:
                    number.in_range:
                      id: doorman_ring_to_open_delay
                      above: 59
                  then:
                    - delay: !lambda "return 5000 + (rand() % 10000);"
                  else:
                    - delay: !lambda "return (id(doorman_ring_to_open_delay).state*1000) + 300;"

              - lock.open: apartment_door


select:
  - id: !extend doorman_ring_to_open_door_trigger
    options:
      - Apartment