# Configurable Options
substitutions:
  name: "doorman-s3"
  friendly_name: "Doorman S3"
  log_level: "INFO"

# Essential ESPHome Configuration Options
esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
  min_version: "2025.5.0"
  project:
    name: "AzonInc.Doorman"
    version: "2025.5.0"
  on_boot:
    priority: 600
    then:
      - lock.template.publish:
          id: entrance_door
          state: LOCKED
      - lock.template.publish:
          id: second_entrance_door
          state: LOCKED

      # Temporary Workaround for ESPHome >= 2025.3.0
      # Prevents WebServer Crash
      - event.trigger:
          id: entrance_doorbell_pattern
          event_type: "default"
      - event.trigger:
          id: second_entrance_doorbell_pattern
          event_type: "default"
      - event.trigger:
          id: apartment_doorbell_pattern
          event_type: "default"
      - event.trigger:
          id: phone_pick_up_pattern
          event_type: "default"


# Enable logging
# Prevent component warning spam
logger:
  level: ${log_level}
  #logs:
  #  component: ERROR # avoids component warning spam
  #  sensor: WARN  # avoids logging debug sensor updates

web_server:
  version: 3
  sorting_groups:
    - id: sorting_group_controls
      name: "Quick Actions"
      sorting_weight: -100

    - id: sorting_group_settings
      name: "Settings - General"
      sorting_weight: -91

    - id: sorting_group_settings_advanced
      name: "Settings - Advanced"
      sorting_weight: -90

    - id: sorting_group_rto_settings
      name: "Settings - Ring To Open"
      sorting_weight: -80

    - id: sorting_group_intercom_settings
      name: "Settings - TC:BUS Indoor Station"
      sorting_weight: -70

    - id: sorting_group_nuki_settings
      name: "Settings - Nuki Lock"
      sorting_weight: -61

    - id: sorting_group_nuki_bridge_settings
      name: "Settings - Nuki Bridge"
      sorting_weight: -60

    - id: sorting_group_system
      name: "Settings - System"
      sorting_weight: -50

    - id: sorting_group_listeners
      name: "Doorman Listeners"
      sorting_weight: -40

    - id: sorting_group_debug_tools
      name: "Debugging Tools"
      sorting_weight: -30

    - id: sorting_group_updates
      name: "Firmware Updates"
      sorting_weight: -20

    - id: sorting_group_nuki
      name: "Information - Nuki Lock"
      sorting_weight: -10

    - id: sorting_group_information
      name: "Information - System"
      sorting_weight: -5

wifi:
  ap:
    ssid: "${friendly_name} Setup"
    password: "Op3n-Sesame!"

captive_portal:

# Improv for easy provisioning
improv_serial:

# Import TC:BUS Component
external_components:
  - source: github://azoninc/doorman@${branch}
    components: [ tc_bus, captive_portal ]
    refresh: 60s

# Setup RMT components
remote_receiver:
  pin:
    number: ${rx_pin}
    mode: INPUT
  filter: 1500us
  idle: 7000us

remote_transmitter:
  pin:
    number: ${tx_pin}
    mode: OUTPUT
  carrier_duty_percent: 100%
  eot_level: false
  on_complete:
    - if:
        condition:
          - switch.is_on: doorman_status_led_bus_activity
        then:
          - script.execute: blink_status_led

# Setup TC:BUS Component
tc_bus:
  id: tc_bus_intercom
  event: "doorman"
  on_command:
    - if:
        condition:
          - switch.is_on: doorman_status_led_bus_activity
        then:
          - script.execute: blink_status_led
  
number:
  - platform: tc_bus
    serial_number:
      id: serial_number
      name: "Serial Number"
      icon: "mdi:numeric"
      disabled_by_default: true
      web_server:
        sorting_group_id: sorting_group_settings
        sorting_weight: -100

  - platform: template
    id: entrance_door_station_id
    name: "Entrance Door Station ID"
    mode : box
    icon: "mdi:counter"
    restore_value: true
    initial_value: '0'
    max_value: 63
    min_value: 0
    step: 1
    optimistic: true
    disabled_by_default: true
    entity_category: CONFIG
    web_server:
      sorting_group_id: sorting_group_settings
      sorting_weight: -99

  - platform: template
    id: second_entrance_door_station_id
    name: "Second Entrance Door Station ID"
    mode : box
    icon: "mdi:counter"
    restore_value: true
    initial_value: '63'
    max_value: 63
    min_value: 0
    step: 1
    optimistic: true
    disabled_by_default: true
    entity_category: CONFIG
    web_server:
      sorting_group_id: sorting_group_settings
      sorting_weight: -98

text:
  - platform: template
    id: entrance_door_before_open_cmds
    name: "Entrance Door Pre-Open-Commands"
    icon: "mdi:link-lock"
    optimistic: true
    min_length: 0
    max_length: 255
    mode: text
    restore_value: true
    initial_value : ""
    disabled_by_default: true
    entity_category: CONFIG
    web_server:
      sorting_group_id: sorting_group_settings_advanced
      sorting_weight: -70

  - platform: template
    id: second_entrance_door_before_open_cmds
    name: "Second Entrance Door Pre-Open-Commands"
    icon: "mdi:link-lock"
    optimistic: true
    min_length: 0
    max_length: 255
    mode: text
    restore_value: true
    initial_value : ""
    disabled_by_default: true
    entity_category: CONFIG
    web_server:
      sorting_group_id: sorting_group_settings_advanced
      sorting_weight: -69


text_sensor:
  - platform: tc_bus
    hardware_version:
      id: doorman_hardware_version
      name: "Doorman Hardware"
      icon: "mdi:router-wireless"
      disabled_by_default: true
      entity_category: DIAGNOSTIC
      web_server:
        sorting_group_id: sorting_group_information
        sorting_weight: -20
    bus_command:
      id: last_bus_command
      name: "Last Bus Command"
      web_server:
        sorting_group_id: sorting_group_listeners
        sorting_weight: -99

  - platform: version
    id: esphome_version
    name: "ESPHome Version"
    icon: mdi:information-box
    hide_timestamp: true
    entity_category: DIAGNOSTIC
    disabled_by_default: true
    web_server:
      sorting_group_id: sorting_group_updates
      sorting_weight: 0

  - platform: template
    id: doorman_firmware_version
    name: "Doorman Firmware Version"
    icon: mdi:information-box
    lambda: |-
      return { ESPHOME_PROJECT_VERSION };
    entity_category: DIAGNOSTIC
    disabled_by_default: true
    web_server:
      sorting_group_id: sorting_group_updates
      sorting_weight: 1

switch:
  - platform: tc_bus
    force_long_door_opener:
      id: use_32_open_door_protocol
      name: "Use 32-Bit Door Protocol"
      icon: mdi:flash-alert
      entity_category: CONFIG
      disabled_by_default: true
      web_server:
        sorting_group_id: sorting_group_settings_advanced
        sorting_weight: -50

  - platform: gpio
    name: Relay
    icon: mdi:electric-switch
    id: doorman_relay
    restore_mode: RESTORE_DEFAULT_OFF
    disabled_by_default: true
    pin: ${relay_pin}
    web_server:
      sorting_group_id: sorting_group_controls
      sorting_weight: 6

  - platform: template
    id: doorman_status_led_bus_activity
    name: "Status LED: Show Bus Activity"
    icon: "mdi:swap-vertical"
    restore_mode: RESTORE_DEFAULT_OFF
    disabled_by_default: true
    optimistic: true
    web_server:
      sorting_group_id: sorting_group_settings_advanced
      sorting_weight: -40


button:
  # System Actions
  - platform: restart
    id: doorman_restart
    entity_category: CONFIG
    name: Restart
    icon: mdi:restart
    disabled_by_default: true
    web_server:
      sorting_group_id: sorting_group_system
      sorting_weight: -2

  - platform: factory_reset
    id: doorman_factory_reset
    name: Restore Factory Settings
    entity_category: CONFIG
    disabled_by_default: true
    web_server:
      sorting_group_id: sorting_group_system
      sorting_weight: 0

output:
  - platform: template
    type: binary
    id: hallway_light_output
    write_action:
      - if:
          condition:
            lambda: !lambda return state;
          then:
            - tc_bus.send:
                type: light
            - delay: 5s
            - light.turn_off: hallway_light

# Onboard Status LEDs
light:
  - platform: status_led
    id: doorman_status_led
    name: Status LED
    icon: "mdi:led-on"
    pin: ${led_pin}
    restore_mode: RESTORE_DEFAULT_OFF
    entity_category: CONFIG
    web_server:
      sorting_group_id: sorting_group_system
      sorting_weight: -9

  - platform: binary
    id: hallway_light
    name: "Hallway Light"
    icon: mdi:lightbulb-on
    output: hallway_light_output
    disabled_by_default: true
    web_server:
      sorting_group_id: sorting_group_controls
      sorting_weight: 4

sensor:
  - platform: uptime
    name: Uptime
    id: doorman_uptime
    disabled_by_default: true
    entity_category: DIAGNOSTIC
    web_server:
      sorting_group_id: sorting_group_information
      sorting_weight: -7

  - platform: wifi_signal
    id: doorman_wifi_signal_db
    update_interval: 60s
    internal: True

  - platform: copy
    id: doorman_wifi_signal
    icon: "mdi:wifi"
    source_id: doorman_wifi_signal_db
    name: "WiFi Signal"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: DIAGNOSTIC
    disabled_by_default: true
    device_class: ""
    web_server:
      sorting_group_id: sorting_group_information
      sorting_weight: -5

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      inverted: true
      mode:
        input: true
        pullup: true
      ignore_strapping_warning: true
    internal: true
    id: doorman_boot_button
    name: "Flash Button"
    icon: "mdi:gesture-tap"
    disabled_by_default: true
    web_server:
      sorting_group_id: sorting_group_listeners
      sorting_weight: 100

  - platform: gpio
    id: doorman_external_button
    name: "External Button"
    icon: "mdi:gesture-tap"
    disabled_by_default: true
    pin:
      number: ${external_button_pin}
      mode:
        pullup: true
        input: true
      inverted: true
    web_server:
      sorting_group_id: sorting_group_listeners
      sorting_weight: 99

  - platform: tc_bus
    id: entrance_doorbell
    name: "Entrance Doorbell"
    type: door_call
    address_lambda: !lambda "return id(entrance_door_station_id).state;"
    auto_off: 0.2s
    disabled_by_default: true
    web_server:
      sorting_group_id: sorting_group_listeners
      sorting_weight: -28

  - platform: tc_bus
    id: second_entrance_doorbell
    name: "Second Entrance Doorbell"
    type: door_call
    address_lambda: !lambda "return id(second_entrance_door_station_id).state;"
    auto_off: 0.2s
    disabled_by_default: true
    web_server:
      sorting_group_id: sorting_group_listeners
      sorting_weight: -27

  - platform: tc_bus
    id: apartment_doorbell
    name: "Apartment Doorbell"
    type: floor_call
    auto_off: 0.2s
    disabled_by_default: true
    web_server:
      sorting_group_id: sorting_group_listeners
      sorting_weight: -29

  - platform: tc_bus
    id: pick_up_phone_door_call
    name: "Pick up phone (door call)"
    icon: "mdi:phone-check"
    type: start_talking_door_call
    address: 255
    auto_off: 0.2s
    disabled_by_default: true
    web_server:
      sorting_group_id: sorting_group_listeners
      sorting_weight: -19

  - platform: tc_bus
    id: hang_up_phone_door_call
    name: "Hang up phone (door call)"
    icon: "mdi:phone-remove"
    type: stop_talking_door_call
    address: 255
    auto_off: 0.2s
    disabled_by_default: true
    web_server:
      sorting_group_id: sorting_group_listeners
      sorting_weight: -18

  - platform: tc_bus
    id: pick_up_phone
    name: "Pick up phone"
    icon: "mdi:phone-check"
    type: start_talking
    address: 255
    auto_off: 0.2s
    disabled_by_default: true
    web_server:
      sorting_group_id: sorting_group_listeners
      sorting_weight: -17

  - platform: tc_bus
    id: hang_up_phone
    name: "Hang up phone"
    icon: "mdi:phone-remove"
    type: stop_talking
    address: 255
    auto_off: 0.2s
    disabled_by_default: true
    web_server:
      sorting_group_id: sorting_group_listeners
      sorting_weight: -16

  - platform: tc_bus
    id: function_button
    name: "Function Button"
    icon: "mdi:circle-outline"
    auto_off: 0.2s
    type: control_function
    payload: 255
    disabled_by_default: true
    web_server:
      sorting_group_id: sorting_group_listeners
      sorting_weight: -6

  - platform: tc_bus
    id: light_button
    name: "Light Button"
    icon: "mdi:white-balance-sunny"
    type: light
    auto_off: 0.2s
    disabled_by_default: true
    web_server:
      sorting_group_id: sorting_group_listeners
      sorting_weight: -7

  - platform: tc_bus
    id: open_entrance_door_button
    internal: true
    type: open_door
    address_lambda: !lambda "return id(entrance_door_station_id).state;"
    serial_number: 255
    auto_off: 5s
    on_press:
      - lock.template.publish:
          id: entrance_door
          state: UNLOCKED
    on_release:
      - lock.template.publish:
          id: entrance_door
          state: LOCKED

  - platform: tc_bus
    id: open_second_entrance_door_button
    internal: true
    type: open_door
    address_lambda: !lambda "return id(second_entrance_door_station_id).state;"
    serial_number: 255
    auto_off: 5s
    on_press:
      - lock.template.publish:
          id: second_entrance_door
          state: UNLOCKED
    on_release:
      - lock.template.publish:
          id: second_entrance_door
          state: LOCKED

lock:
  - platform: template
    id: entrance_door
    name: "Entrance Door"
    icon: mdi:door
    lock_action:
      - lock.template.publish:
          id: entrance_door
          state: LOCKED
    unlock_action:
      - lock.template.publish:
          id: entrance_door
          state: UNLOCKED
      - script.execute:
          id: send_command_chain
          command_list: !lambda "return id(entrance_door_before_open_cmds).state;"
      - tc_bus.send:
          type: open_door
          address: !lambda "return id(entrance_door_station_id).state;"
      - delay: 5s
      - lock.template.publish:
          id: entrance_door
          state: LOCKED
    web_server:
      sorting_group_id: sorting_group_controls
      sorting_weight: 1

  - platform: template
    id: second_entrance_door
    name: "Second Entrance Door"
    icon: mdi:door
    disabled_by_default: true
    lock_action:
      - lock.template.publish:
          id: second_entrance_door
          state: LOCKED
    unlock_action:
      - lock.template.publish:
          id: second_entrance_door
          state: UNLOCKED
      - script.execute:
          id: send_command_chain
          command_list: !lambda "return id(second_entrance_door_before_open_cmds).state;"
      - tc_bus.send:
          type: open_door
          address: !lambda "return id(second_entrance_door_station_id).state;"
      - delay: 5s
      - lock.template.publish:
          id: second_entrance_door
          state: LOCKED
    web_server:
      sorting_group_id: sorting_group_controls
      sorting_weight: 2


event:
  - platform: template
    id: entrance_doorbell_pattern
    name: "Entrance Doorbell"
    icon: "mdi:doorbell"
    device_class: DOORBELL
    event_types:
      - "default"
    web_server:
      sorting_group_id: sorting_group_listeners
      sorting_weight: -30

  - platform: template
    id: second_entrance_doorbell_pattern
    name: "Second Entrance Doorbell"
    icon: "mdi:doorbell"
    device_class: DOORBELL
    event_types:
      - "default"
    web_server:
      sorting_group_id: sorting_group_listeners
      sorting_weight: -40

  - platform: template
    id: apartment_doorbell_pattern
    name: "Apartment Doorbell"
    icon: "mdi:doorbell"
    device_class: DOORBELL
    event_types:
      - "default"
    web_server:
      sorting_group_id: sorting_group_listeners
      sorting_weight: -50

  - platform: template
    id: phone_pick_up_pattern
    name: "Phone pick up"
    icon: "mdi:phone-incoming-outgoing"
    event_types:
      - "default"
    web_server:
      sorting_group_id: sorting_group_listeners
      sorting_weight: -20

script:
  - id: blink_status_led
    mode: restart
    then:
      - light.turn_off: doorman_status_led
      - light.turn_on: doorman_status_led
      - delay: 100ms
      - light.turn_off: doorman_status_led

  - id: send_command_chain
    parameters:
      command_list: string
    then:
      - lambda: |-
          size_t start = 0;
          size_t end;

          while ((end = command_list.find(';', start)) != std::string::npos) {
              std::string token = command_list.substr(start, end - start);

              // Remove non-hex characters
              token.erase(std::remove_if(token.begin(), token.end(), [](char c) {
                  return !std::isxdigit(static_cast<unsigned char>(c));
              }), token.end());

              if (token.length() == 4 || token.length() == 8) {
                  const char* str = token.c_str();
                  char* endptr = nullptr;
                  errno = 0;  // Reset errno before call
                  unsigned long number = std::strtoul(str, &endptr, 16);

                  // Check if entire string was converted and no errors occurred
                  if (endptr == str + token.size() && errno == 0) {
                      if (token.length() == 8) {
                          id(tc_bus_intercom)->send_command(number, true);
                      } else {
                          id(tc_bus_intercom)->send_command(number);
                      }
                  }
              }
              start = end + 1;
          }

          // Handle last token
          std::string token = command_list.substr(start);
          token.erase(std::remove_if(token.begin(), token.end(), [](char c) {
              return !std::isxdigit(static_cast<unsigned char>(c));
          }), token.end());

          if (token.length() == 4 || token.length() == 8) {
              const char* str = token.c_str();
              char* endptr = nullptr;
              errno = 0;
              unsigned long number = std::strtoul(str, &endptr, 16);
              if (endptr == str + token.size() && errno == 0) {
                  if (token.length() == 8) {
                      id(tc_bus_intercom)->send_command(number, true);
                  } else {
                      id(tc_bus_intercom)->send_command(number);
                  }
              }
          }

  - id: update_led
    then:
      - logger.log: "Conditionally set LED State"
      - light.turn_off:
          id: doorman_rgb_status_led
          transition_length: 1s
      # TODO: Restore specific state conditionally
      # Extended by addons